The Basics of NumPy Arrays


We'll cover a few categories of basic array manipulations here:

Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays
Indexing of arrays: Getting and setting the value of individual array elements
Slicing of arrays: Getting and setting smaller subarrays within a larger array
Reshaping of arrays: Changing the shape of a given array
Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many

NumPy Array Attributes
First let's discuss some useful array attributes. We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array. We'll use NumPy's random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):

In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [3]:
print("dtype:", x3.dtype)

dtype: int64


In [4]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


Array Indexing: Accessing Single Elements
If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar. In a one-dimensional array, the 
 value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [5]:
x1


array([5, 0, 3, 3, 7, 9])

In [12]:
print(x1[0])

5


In [13]:
print(x1[4])

7


In [15]:
print(x1[-1])

9


In [16]:
print(x1[-2])

7


In [17]:
print(x1[-2])

7


In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:



In [10]:
x2


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [18]:
print(x2[0, 0])

3


In [19]:
print(x2[2, 0])

1


In [21]:
print(x2[2, -1])

7


Values can also be modified using any of the above index notation:



In [22]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [23]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

### One-Dimensional Subarrays

Here are some examples of accessing elements in one-dimensional subarrays:

In [24]:
x1

array([3, 0, 3, 3, 7, 9])

In [25]:
x1[:3]  # first three elements

array([3, 0, 3])

In [26]:
x1[3:]  # elements after index 3

array([3, 7, 9])

In [27]:
x1[1:4]  # middle subarray

array([0, 3, 3])

In [28]:
x1[::2]  # every second element

array([3, 3, 7])

In [29]:
x1[1::2]  # every second element, starting at index 1

array([0, 3, 9])

A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array:

In [30]:
x1[::-1]  # all elements, reversed

array([9, 7, 3, 3, 0, 3])

In [31]:
x1[4::-2]  # every second element from index 4, reversed

array([7, 3, 3])

### Multidimensional Subarrays

Multidimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [32]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [33]:
x2[:2, :3]  # first two rows & three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [34]:
x2[:3, ::2]  # three rows, every second column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [35]:
x2[::-1, ::-1]  # all rows & columns, reversed

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns

One commonly needed routine is accessing single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (`:`):

In [36]:
x2[:, 0]  # first column of x2

array([12,  7,  1])

In [37]:
x2[0, :]  # first row of x2

array([12,  5,  2,  4])

In the case of row access, the empty slice can be omitted for a more compact syntax:

In [38]:
x2[0]  # equivalent to x2[0, :]

array([12,  5,  2,  4])

In [39]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [40]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [41]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [42]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Creating Copies of Arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the `copy` method:

In [43]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [44]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Reshaping of Arrays

In [45]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
x = np.array([1, 2, 3])
x.reshape((1, 3))  # row vector via reshape

array([[1, 2, 3]])

In [47]:
x.reshape((3, 1))  # column vector via reshape

array([[1],
       [2],
       [3]])

In [48]:
x[np.newaxis, :]  # row vector via newaxis

array([[1, 2, 3]])

In [49]:
x[:, np.newaxis]  # column vector via newaxis

array([[1],
       [2],
       [3]])

Array Concatenation and Splitting

Concatenation of Arrays

In [50]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:


In [51]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


And it can be used for two-dimensional arrays:

In [53]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [54]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [55]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:

In [58]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])